name: MySQL CRUD Ops Test

on:
  push:
    branches: 
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -uroot -proot"
          --health-interval=5s
          --health-timeout=5s
          --health-retries=20  

    env:
      DB_HOST: 127.0.0.1
      DB_PORT: 3306
      DB_USER: root
      DB_PWD: root
      DB_NAME: testdb

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: npm

      - name: Install deps
        run: npm ci

      - name: setup DB
        run: |
          mysql -h 127.0.01 -proot testdb <<'EOF'
          CREATE TABLE products ('
          id INT AUTO_INCREMENT PRIMARY KEY,
          name VARCHAR(255) NOT NULL,
          price DECIMAL(10, 2) NOT NULL
          );
          
          INSERT INTO products (name, price) VALUES
          ('Rice', 5000),
          ('Beans', 4000),
          ('Yam', 3000);
          EOF
      - name: Run tests against db
        run: npm test    